/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abogados;

/**
 *
 * @author ASUS
 */
public class abogadoInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form abogadoInterfaz
     */
    public abogadoInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnModificarAbodagos1 = new javax.swing.JButton();
        btnContratosEspera = new javax.swing.JButton();
        btnContratosVigentes1 = new javax.swing.JButton();
        btnCasosGratuitos = new javax.swing.JButton();
        btnAsistenteAsignado = new javax.swing.JButton();
        btnOficinaAsignada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelLOGO = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(205, 133, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 1050, 510));

        jPanel3.setBackground(new java.awt.Color(25, 25, 112));

        btnModificarAbodagos1.setBackground(new java.awt.Color(102, 153, 255));
        btnModificarAbodagos1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnModificarAbodagos1.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarAbodagos1.setText("Modificar");
        btnModificarAbodagos1.setBorder(null);
        btnModificarAbodagos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAbodagos1ActionPerformed(evt);
            }
        });

        btnContratosEspera.setBackground(new java.awt.Color(102, 153, 255));
        btnContratosEspera.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnContratosEspera.setForeground(new java.awt.Color(255, 255, 255));
        btnContratosEspera.setText("Contratos en Espera");
        btnContratosEspera.setBorder(null);
        btnContratosEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratosEsperaActionPerformed(evt);
            }
        });

        btnContratosVigentes1.setBackground(new java.awt.Color(102, 153, 255));
        btnContratosVigentes1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnContratosVigentes1.setForeground(new java.awt.Color(255, 255, 255));
        btnContratosVigentes1.setText("Contratos Vigentes");
        btnContratosVigentes1.setBorder(null);
        btnContratosVigentes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContratosVigentes1ActionPerformed(evt);
            }
        });

        btnCasosGratuitos.setBackground(new java.awt.Color(102, 153, 255));
        btnCasosGratuitos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCasosGratuitos.setForeground(new java.awt.Color(255, 255, 255));
        btnCasosGratuitos.setText("Casos Gratuitos");
        btnCasosGratuitos.setBorder(null);
        btnCasosGratuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCasosGratuitosActionPerformed(evt);
            }
        });

        btnAsistenteAsignado.setBackground(new java.awt.Color(102, 153, 255));
        btnAsistenteAsignado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAsistenteAsignado.setForeground(new java.awt.Color(255, 255, 255));
        btnAsistenteAsignado.setText("Asistente Asignado");
        btnAsistenteAsignado.setBorder(null);
        btnAsistenteAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsistenteAsignadoActionPerformed(evt);
            }
        });

        btnOficinaAsignada.setBackground(new java.awt.Color(102, 153, 255));
        btnOficinaAsignada.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnOficinaAsignada.setForeground(new java.awt.Color(255, 255, 255));
        btnOficinaAsignada.setText("Oficina Asignada");
        btnOficinaAsignada.setBorder(null);
        btnOficinaAsignada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOficinaAsignadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnModificarAbodagos1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btnContratosVigentes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnContratosEspera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnAsistenteAsignado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnOficinaAsignada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCasosGratuitos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnModificarAbodagos1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnContratosVigentes1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnContratosEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAsistenteAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnOficinaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnCasosGratuitos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 510));

        jLabel1.setFont(new java.awt.Font("Microsoft Yi Baiti", 3, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOGADOS-ECU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 650, -1));

        jLabelLOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escala-de-justicia.png"))); // NOI18N
        jPanel1.add(jLabelLOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maps-and-location.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VICENTE PINZON Y LUIS DE LA CEDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, 430, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContratosEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratosEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContratosEsperaActionPerformed

    private void btnModificarAbodagos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAbodagos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarAbodagos1ActionPerformed

    private void btnContratosVigentes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContratosVigentes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContratosVigentes1ActionPerformed

    private void btnCasosGratuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCasosGratuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCasosGratuitosActionPerformed

    private void btnAsistenteAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsistenteAsignadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAsistenteAsignadoActionPerformed

    private void btnOficinaAsignadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOficinaAsignadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOficinaAsignadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abogadoInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsistenteAsignado;
    private javax.swing.JButton btnCasosGratuitos;
    private javax.swing.JButton btnContratosEspera;
    private javax.swing.JButton btnContratosVigentes1;
    private javax.swing.JButton btnModificarAbodagos1;
    private javax.swing.JButton btnOficinaAsignada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelLOGO;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
