/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package abogados;

import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class abogadoInterfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form abogadoInterfaz
     */
    public abogadoInterfaz2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        VentanaFondo = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        VentanaModificar = new javax.swing.JPanel();
        txtNombres = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JLabel();
        txtCedula = new javax.swing.JLabel();
        txtFechaNacimiento = new javax.swing.JLabel();
        txtGenero = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JLabel();
        txtfoto = new javax.swing.JLabel();
        txtCostoHora = new javax.swing.JLabel();
        txtGratuidad = new javax.swing.JLabel();
        txtTitulos = new javax.swing.JLabel();
        txtPrimerNombre = new javax.swing.JTextField();
        txtSegundoNombre = new javax.swing.JTextField();
        txtPrimerNombre1 = new javax.swing.JTextField();
        txtPrimerNombre2 = new javax.swing.JTextField();
        txtPrimerNombre3 = new javax.swing.JTextField();
        txtPrimerNombre4 = new javax.swing.JTextField();
        txtPrimerNombre6 = new javax.swing.JTextField();
        txtPrimerNombre7 = new javax.swing.JTextField();
        txtPrimerNombre8 = new javax.swing.JTextField();
        txtPrimerNombre10 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        rSFotoSquare1 = new rojerusan.RSFotoSquare();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtModificar = new javax.swing.JTextField();
        txtContratosVigentes = new javax.swing.JTextField();
        txtContratosEspera = new javax.swing.JTextField();
        txtAsistenteAsignado = new javax.swing.JTextField();
        txtOficinaAsignada = new javax.swing.JTextField();
        txtCasosGratuitos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pexels-august-de-richelieu-4427430 (1).jpg"))); // NOI18N

        javax.swing.GroupLayout VentanaFondoLayout = new javax.swing.GroupLayout(VentanaFondo);
        VentanaFondo.setLayout(VentanaFondoLayout);
        VentanaFondoLayout.setHorizontalGroup(
            VentanaFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaFondoLayout.setVerticalGroup(
            VentanaFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(VentanaFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 510));

        VentanaModificar.setBackground(new java.awt.Color(0, 102, 102));

        txtNombres.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtNombres.setText("Nombres:");

        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtApellidos.setText("Apellidos:");

        txtCedula.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtCedula.setText("Cédula:");

        txtFechaNacimiento.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtFechaNacimiento.setText("Fecha de nacimiento:");

        txtGenero.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtGenero.setText("Género:");

        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtDireccion.setText("Dirección:");

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtTelefono.setText("Teléfono:");

        txtfoto.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtfoto.setText("Seleccione una foto:");

        txtCostoHora.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtCostoHora.setText("Costo por hora:");

        txtGratuidad.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtGratuidad.setText("Gratuidad:");

        txtTitulos.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtTitulos.setText("Titulos:");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Masculino");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Femenino");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("SI");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("NO");

        javax.swing.GroupLayout VentanaModificarLayout = new javax.swing.GroupLayout(VentanaModificar);
        VentanaModificar.setLayout(VentanaModificarLayout);
        VentanaModificarLayout.setHorizontalGroup(
            VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombres)
                            .addComponent(txtApellidos))
                        .addGap(30, 30, 30)
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addComponent(txtPrimerNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrimerNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addComponent(txtPrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarLayout.createSequentialGroup()
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addComponent(txtFechaNacimiento)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrimerNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addComponent(txtCedula)
                                .addGap(50, 50, 50)
                                .addComponent(txtPrimerNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtGenero))
                                .addGap(26, 26, 26)
                                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPrimerNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 247, Short.MAX_VALUE)
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                                        .addComponent(txtTitulos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPrimerNombre10, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                                        .addComponent(txtTelefono)
                                        .addGap(71, 71, 71)
                                        .addComponent(txtPrimerNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarLayout.createSequentialGroup()
                                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarLayout.createSequentialGroup()
                                                .addComponent(txtCostoHora)
                                                .addGap(18, 18, 18))
                                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                                .addComponent(txtGratuidad)
                                                .addGap(63, 63, 63)))
                                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrimerNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addComponent(txtfoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSFotoSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40))))))
        );
        VentanaModificarLayout.setVerticalGroup(
            VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VentanaModificarLayout.createSequentialGroup()
                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtPrimerNombre)
                                .addComponent(txtSegundoNombre))
                            .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaModificarLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtApellidos)
                                    .addComponent(txtPrimerNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrimerNombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VentanaModificarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfoto)
                                .addGap(17, 17, 17))))
                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(rSFotoSquare1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedula)
                    .addComponent(txtTelefono)
                    .addComponent(txtPrimerNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimerNombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaNacimiento)
                    .addComponent(txtCostoHora)
                    .addComponent(txtPrimerNombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimerNombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtGenero)
                                .addComponent(jRadioButton1)
                                .addComponent(jRadioButton2))
                            .addComponent(txtGratuidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion)
                            .addComponent(txtTitulos)
                            .addComponent(txtPrimerNombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrimerNombre10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))
                    .addGroup(VentanaModificarLayout.createSequentialGroup()
                        .addGroup(VentanaModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel2.add(VentanaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 510));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 510));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 1050, 510));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));

        txtModificar.setEditable(false);
        txtModificar.setBackground(new java.awt.Color(0, 0, 102));
        txtModificar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtModificar.setForeground(new java.awt.Color(255, 255, 255));
        txtModificar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtModificar.setText("Modificar");
        txtModificar.setBorder(null);
        txtModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModificarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtModificarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtModificarMouseExited(evt);
            }
        });
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });

        txtContratosVigentes.setEditable(false);
        txtContratosVigentes.setBackground(new java.awt.Color(0, 0, 102));
        txtContratosVigentes.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtContratosVigentes.setForeground(new java.awt.Color(255, 255, 255));
        txtContratosVigentes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContratosVigentes.setText("Contratos Vigentes");
        txtContratosVigentes.setBorder(null);
        txtContratosVigentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtContratosVigentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtContratosVigentesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtContratosVigentesMouseExited(evt);
            }
        });
        txtContratosVigentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContratosVigentesActionPerformed(evt);
            }
        });

        txtContratosEspera.setEditable(false);
        txtContratosEspera.setBackground(new java.awt.Color(0, 0, 102));
        txtContratosEspera.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtContratosEspera.setForeground(new java.awt.Color(255, 255, 255));
        txtContratosEspera.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContratosEspera.setText("Contratos en Espera");
        txtContratosEspera.setBorder(null);
        txtContratosEspera.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtContratosEspera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtContratosEsperaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtContratosEsperaMouseExited(evt);
            }
        });
        txtContratosEspera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContratosEsperaActionPerformed(evt);
            }
        });

        txtAsistenteAsignado.setEditable(false);
        txtAsistenteAsignado.setBackground(new java.awt.Color(0, 0, 102));
        txtAsistenteAsignado.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtAsistenteAsignado.setForeground(new java.awt.Color(255, 255, 255));
        txtAsistenteAsignado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAsistenteAsignado.setText("Asistente Asignado");
        txtAsistenteAsignado.setBorder(null);
        txtAsistenteAsignado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtAsistenteAsignado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtAsistenteAsignadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtAsistenteAsignadoMouseExited(evt);
            }
        });
        txtAsistenteAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAsistenteAsignadoActionPerformed(evt);
            }
        });

        txtOficinaAsignada.setEditable(false);
        txtOficinaAsignada.setBackground(new java.awt.Color(0, 0, 102));
        txtOficinaAsignada.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtOficinaAsignada.setForeground(new java.awt.Color(255, 255, 255));
        txtOficinaAsignada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtOficinaAsignada.setText("Oficina Asignada");
        txtOficinaAsignada.setBorder(null);
        txtOficinaAsignada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtOficinaAsignada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtOficinaAsignadaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtOficinaAsignadaMouseExited(evt);
            }
        });
        txtOficinaAsignada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOficinaAsignadaActionPerformed(evt);
            }
        });

        txtCasosGratuitos.setEditable(false);
        txtCasosGratuitos.setBackground(new java.awt.Color(0, 0, 102));
        txtCasosGratuitos.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        txtCasosGratuitos.setForeground(new java.awt.Color(255, 255, 255));
        txtCasosGratuitos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCasosGratuitos.setText("Casos Gratuitos");
        txtCasosGratuitos.setBorder(null);
        txtCasosGratuitos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtCasosGratuitos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtCasosGratuitosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtCasosGratuitosMouseExited(evt);
            }
        });
        txtCasosGratuitos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCasosGratuitosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtContratosEspera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(txtAsistenteAsignado)
            .addComponent(txtCasosGratuitos, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtOficinaAsignada, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtContratosVigentes, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(txtModificar)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContratosVigentes, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtContratosEspera, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAsistenteAsignado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtOficinaAsignada, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCasosGratuitos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 510));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOGADOS-ECU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 700, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maps-and-location.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VICENTE PINZON Y LUIS DE LA CEDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 710, 430, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escala-de-justicia.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 130, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContratosVigentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContratosVigentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContratosVigentesActionPerformed

    private void txtContratosVigentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContratosVigentesMouseExited
        txtContratosVigentes.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtContratosVigentesMouseExited

    private void txtContratosVigentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContratosVigentesMouseEntered
        txtContratosVigentes.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtContratosVigentesMouseEntered

    private void txtAsistenteAsignadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAsistenteAsignadoMouseEntered
        txtAsistenteAsignado.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtAsistenteAsignadoMouseEntered

    private void txtAsistenteAsignadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAsistenteAsignadoMouseExited
        txtAsistenteAsignado.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtAsistenteAsignadoMouseExited

    private void txtAsistenteAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsistenteAsignadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsistenteAsignadoActionPerformed

    private void txtOficinaAsignadaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOficinaAsignadaMouseEntered
        txtOficinaAsignada.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtOficinaAsignadaMouseEntered

    private void txtOficinaAsignadaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOficinaAsignadaMouseExited
        txtOficinaAsignada.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtOficinaAsignadaMouseExited

    private void txtOficinaAsignadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOficinaAsignadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOficinaAsignadaActionPerformed

    private void txtContratosEsperaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContratosEsperaMouseEntered
        txtContratosEspera.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtContratosEsperaMouseEntered

    private void txtContratosEsperaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtContratosEsperaMouseExited
        txtContratosEspera.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtContratosEsperaMouseExited

    private void txtContratosEsperaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContratosEsperaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContratosEsperaActionPerformed

    private void txtCasosGratuitosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCasosGratuitosMouseEntered
        txtCasosGratuitos.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtCasosGratuitosMouseEntered

    private void txtCasosGratuitosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCasosGratuitosMouseExited
        txtCasosGratuitos.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtCasosGratuitosMouseExited

    private void txtCasosGratuitosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCasosGratuitosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCasosGratuitosActionPerformed

    private void txtModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseEntered
        txtModificar.setBackground(new Color(0,0,153));
    }//GEN-LAST:event_txtModificarMouseEntered

    private void txtModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseExited
        txtModificar.setBackground(new Color(0,0,102));
    }//GEN-LAST:event_txtModificarMouseExited

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void txtModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseClicked
        VentanaFondo.setVisible(false);
        VentanaModificar.setVisible(true);
        //Poner más ventanas
        
    }//GEN-LAST:event_txtModificarMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        VentanaFondo.setVisible(true);
        VentanaModificar.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(abogadoInterfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new abogadoInterfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel VentanaFondo;
    private javax.swing.JPanel VentanaModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private rojerusan.RSFotoSquare rSFotoSquare1;
    private javax.swing.JLabel txtApellidos;
    private javax.swing.JTextField txtAsistenteAsignado;
    private javax.swing.JTextField txtCasosGratuitos;
    private javax.swing.JLabel txtCedula;
    private javax.swing.JTextField txtContratosEspera;
    private javax.swing.JTextField txtContratosVigentes;
    private javax.swing.JLabel txtCostoHora;
    private javax.swing.JLabel txtDireccion;
    private javax.swing.JLabel txtFechaNacimiento;
    private javax.swing.JLabel txtGenero;
    private javax.swing.JLabel txtGratuidad;
    private javax.swing.JTextField txtModificar;
    private javax.swing.JLabel txtNombres;
    private javax.swing.JTextField txtOficinaAsignada;
    private javax.swing.JTextField txtPrimerNombre;
    private javax.swing.JTextField txtPrimerNombre1;
    private javax.swing.JTextField txtPrimerNombre10;
    private javax.swing.JTextField txtPrimerNombre2;
    private javax.swing.JTextField txtPrimerNombre3;
    private javax.swing.JTextField txtPrimerNombre4;
    private javax.swing.JTextField txtPrimerNombre6;
    private javax.swing.JTextField txtPrimerNombre7;
    private javax.swing.JTextField txtPrimerNombre8;
    private javax.swing.JTextField txtSegundoNombre;
    private javax.swing.JLabel txtTelefono;
    private javax.swing.JLabel txtTitulos;
    private javax.swing.JLabel txtfoto;
    // End of variables declaration//GEN-END:variables
}
