/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abogados;

import clases.TIPO_diplomnma;
import clases.abogado;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author KEVIN SANCHEZ
 */
public class administradorInterfaz extends javax.swing.JFrame {
ArrayList mostrar  = new ArrayList();
    /**
     * Creates new form administradorInterfaz
     */
    public administradorInterfaz() {
        initComponents();
//        setLocationRelativeTo(this);
        questnombre.setVisible(false);
        JPcrud_abg.setVisible(false);
    }
    TIPO_diplomnma change = new TIPO_diplomnma();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void limpiar(){
        DefaultTableModel tb = (DefaultTableModel) Tabla_Tipos.getModel();
            int a = Tabla_Tipos.getRowCount()-1;
            for (int i = a; i >= 0; i--) {          
            tb.removeRow(tb.getRowCount()-1);
        }
    }
    
     public void mostrarpersonas(ArrayList <TIPO_diplomnma> lista_tipo) {
        // Para darle forma al modelo de la tabla
        DefaultTableModel mTabla;
        mTabla = (DefaultTableModel) Tabla_Tipos.getModel();
        mTabla.setNumRows(0);
        // Uso de una expresion landa
        lista_tipo.stream().forEach(tipos -> {
            String[] filaNueva = {String.valueOf(tipos.getID_diploma()), tipos.getNombre_diplo()};
            mTabla.addRow(filaNueva);
        });
            Tabla_Tipos.setModel(mTabla);
        
    }
        
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        questnombre = new javax.swing.JDialog();
        TXT_nuevo_tipo = new javax.swing.JTextField();
        jButtonModificarA10 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JPfondo_Inicial = new javax.swing.JPanel();
        JPcrud_abg = new javax.swing.JPanel();
        jButtonModificarA6 = new javax.swing.JButton();
        jButtonModificarA7 = new javax.swing.JButton();
        jButtonModificarA8 = new javax.swing.JButton();
        jButtonModificarA9 = new javax.swing.JButton();
        jButtonModificarA11 = new javax.swing.JButton();
        jScrollPaneCam = new javax.swing.JScrollPane();
        TablaR = new javax.swing.JTable();
        JP_fondo_especialidad = new javax.swing.JPanel();
        jButtonModificarA12 = new javax.swing.JButton();
        jButtonModificarA13 = new javax.swing.JButton();
        jButtonModificarA14 = new javax.swing.JButton();
        jButtonModificarA15 = new javax.swing.JButton();
        jButtonModificarA16 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JTxt_ingreso_diplo = new javax.swing.JTextField();
        jScrollPaneCam1 = new javax.swing.JScrollPane();
        Tabla_Tipos = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        questnombre.setTitle("RESULTADO DE LA BUSQUEDA");

        TXT_nuevo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_nuevo_tipoActionPerformed(evt);
            }
        });

        jButtonModificarA10.setBackground(new java.awt.Color(102, 153, 255));
        jButtonModificarA10.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA10.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA10.setText("Modificar");
        jButtonModificarA10.setBorder(null);
        jButtonModificarA10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA10ActionPerformed(evt);
            }
        });

        jLabel5.setText("NOMBRE:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("MODIFICACIÓN");

        javax.swing.GroupLayout questnombreLayout = new javax.swing.GroupLayout(questnombre.getContentPane());
        questnombre.getContentPane().setLayout(questnombreLayout);
        questnombreLayout.setHorizontalGroup(
            questnombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questnombreLayout.createSequentialGroup()
                .addGroup(questnombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(questnombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(questnombreLayout.createSequentialGroup()
                            .addGap(191, 191, 191)
                            .addComponent(jButtonModificarA10, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(questnombreLayout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(TXT_nuevo_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        questnombreLayout.setVerticalGroup(
            questnombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(questnombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(questnombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXT_nuevo_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jButtonModificarA10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(205, 133, 63));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPfondo_Inicial.setBackground(new java.awt.Color(255, 255, 255));
        JPfondo_Inicial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPcrud_abg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificarA6.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA6.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA6.setText("INGRESAR");
        jButtonModificarA6.setBorder(null);
        JPcrud_abg.add(jButtonModificarA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 140, 50));

        jButtonModificarA7.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA7.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA7.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA7.setText("MOSTRAR");
        jButtonModificarA7.setBorder(null);
        jButtonModificarA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA7ActionPerformed(evt);
            }
        });
        JPcrud_abg.add(jButtonModificarA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 140, 50));

        jButtonModificarA8.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA8.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA8.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA8.setText("BUSCAR");
        jButtonModificarA8.setBorder(null);
        JPcrud_abg.add(jButtonModificarA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 460, 140, 50));

        jButtonModificarA9.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA9.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA9.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA9.setText("MODIFICAR");
        jButtonModificarA9.setBorder(null);
        JPcrud_abg.add(jButtonModificarA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 460, 140, 50));

        jButtonModificarA11.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA11.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA11.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA11.setText("ELIMINAR");
        jButtonModificarA11.setBorder(null);
        JPcrud_abg.add(jButtonModificarA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 140, 50));

        TablaR.setBackground(new java.awt.Color(255, 160, 122));
        TablaR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        TablaR.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID_ABG", "CEDULA", "NOMBRE", "APELLIDO", "TELEFONO", "GRATUIDAD", "PUNTUACIÓN", "EDAD", "COSTO X HORAS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TablaR.setRowHeight(30);
        jScrollPaneCam.setViewportView(TablaR);

        JPcrud_abg.add(jScrollPaneCam, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 880, 330));

        JPfondo_Inicial.add(JPcrud_abg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        JP_fondo_especialidad.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonModificarA12.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA12.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA12.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA12.setText("INGRESAR");
        jButtonModificarA12.setBorder(null);
        jButtonModificarA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA12ActionPerformed(evt);
            }
        });
        JP_fondo_especialidad.add(jButtonModificarA12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 140, 50));

        jButtonModificarA13.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA13.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA13.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA13.setText("MODIFICAR");
        jButtonModificarA13.setBorder(null);
        jButtonModificarA13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA13ActionPerformed(evt);
            }
        });
        JP_fondo_especialidad.add(jButtonModificarA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 140, 50));

        jButtonModificarA14.setBackground(new java.awt.Color(188, 143, 143));
        jButtonModificarA14.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA14.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA14.setText("BUSCAR");
        jButtonModificarA14.setBorder(null);
        jButtonModificarA14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA14ActionPerformed(evt);
            }
        });
        JP_fondo_especialidad.add(jButtonModificarA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 90, 40));

        jButtonModificarA15.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA15.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA15.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA15.setText("MOSTRAR");
        jButtonModificarA15.setBorder(null);
        jButtonModificarA15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA15ActionPerformed(evt);
            }
        });
        JP_fondo_especialidad.add(jButtonModificarA15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 140, 50));

        jButtonModificarA16.setBackground(new java.awt.Color(128, 0, 0));
        jButtonModificarA16.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButtonModificarA16.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModificarA16.setText("ELIMINAR");
        jButtonModificarA16.setBorder(null);
        jButtonModificarA16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarA16ActionPerformed(evt);
            }
        });
        JP_fondo_especialidad.add(jButtonModificarA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 140, 50));

        jLabel4.setText("NOMBRE DE LA ESPECIALIZACIÓN");
        JP_fondo_especialidad.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 30));

        JTxt_ingreso_diplo.setForeground(new java.awt.Color(204, 204, 204));
        JTxt_ingreso_diplo.setText("NOMBRE");
        JP_fondo_especialidad.add(JTxt_ingreso_diplo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 150, 40));

        Tabla_Tipos.setBackground(new java.awt.Color(255, 160, 122));
        Tabla_Tipos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        Tabla_Tipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID_TIPO", "NOMBRE_TIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Tabla_Tipos.setRowHeight(30);
        Tabla_Tipos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla_TiposMouseClicked(evt);
            }
        });
        jScrollPaneCam1.setViewportView(Tabla_Tipos);

        JP_fondo_especialidad.add(jScrollPaneCam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 470, 330));

        JPfondo_Inicial.add(JP_fondo_especialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 550));

        jPanel1.add(JPfondo_Inicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 980, 550));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/escala-de-justicia.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ABOGADOS-ECU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/maps-and-location.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VICENTE PINZON Y LUIS DE LA CEDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 720, 430, 40));

        jPanel2.setBackground(new java.awt.Color(25, 25, 112));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(25, 25, 112));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ASISTENTES");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 40));

        jPanel4.setBackground(new java.awt.Color(25, 25, 112));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ABOGADOS");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 40));

        jPanel5.setBackground(new java.awt.Color(25, 25, 112));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CLIENTES");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 40));

        jPanel6.setBackground(new java.awt.Color(25, 25, 112));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("ESPECIALIZACIONES");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 180, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 180, 550));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 30, 63, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1155, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA7ActionPerformed
        abogado abg_usuario = new abogado();
        DefaultTableModel modelo = (DefaultTableModel) TablaR.getModel();
        try {
            
            mostrar = abg_usuario.Listar();
            if(mostrar.isEmpty()){
                JOptionPane.showMessageDialog(null,"NO HAY NINGUN ABOGADO REGISTRADO4");
            }else{
                mostrarpersonas(mostrar);
            }
        } catch (SQLException ex){
            Logger.getLogger(administradorInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            
        }
    }//GEN-LAST:event_jButtonModificarA7ActionPerformed

    private void jButtonModificarA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA12ActionPerformed
            if(JTxt_ingreso_diplo.getText().equals("")){
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR UN TIPO DE DIPLOMA");
        }else{
            TIPO_diplomnma tipos = new TIPO_diplomnma();
            tipos.setNombre_diplo(JTxt_ingreso_diplo.getText());
            try {
                tipos.Ingresar();
                ArrayList <TIPO_diplomnma> lista_tipo = new ArrayList();
                lista_tipo = tipos.mostrar();
                mostrarpersonas(lista_tipo);
            } catch (SQLException ex) {
                Logger.getLogger(administradorInterfaz.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonModificarA12ActionPerformed

    private void jButtonModificarA15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA15ActionPerformed
         TIPO_diplomnma tipos2 = new TIPO_diplomnma();
    try {
        ArrayList <TIPO_diplomnma> lista_tipo = new ArrayList();
        lista_tipo = tipos2.mostrar();
        if(lista_tipo.isEmpty()){
            JOptionPane.showMessageDialog(null,"NO HAY NINGUNA ESPECIALIDAD REGISTRADA");
        }else{
            mostrarpersonas(lista_tipo);
        }
            
    } catch (SQLException ex) {
        Logger.getLogger(administradorInterfaz.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButtonModificarA15ActionPerformed

    private void jButtonModificarA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA4ActionPerformed
        JPcrud_abg.setVisible(false);
        JP_fondo_especialidad.setVisible(true);
    }//GEN-LAST:event_jButtonModificarA4ActionPerformed

    private void jButtonModificarA1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarA1MouseEntered

    }//GEN-LAST:event_jButtonModificarA1MouseEntered

    private void jButtonModificarA1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonModificarA1MouseExited

    }//GEN-LAST:event_jButtonModificarA1MouseExited

    private void jButtonModificarA16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA16ActionPerformed
        TIPO_diplomnma eliminar = new TIPO_diplomnma();
        int seleccionado = -1;
        seleccionado = Tabla_Tipos.getSelectedRow();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        } else {
            int response = JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar esta información?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {
                try {
                    System.out.println(Tabla_Tipos.getValueAt(seleccionado, 0).toString());
                    eliminar.setID_diploma(Integer.parseInt(Tabla_Tipos.getValueAt(seleccionado, 0).toString()));
                    eliminar.ELIMINAR();
                    JOptionPane.showMessageDialog(null, "La persona fue eliminada exitosamente");
                } catch (SQLException ex) {
                    Logger.getLogger(administradorInterfaz.class.getName()).log(Level.SEVERE, null, ex);
                     JOptionPane.showMessageDialog(null, "OCURRIO UN ERROR EN EL PROCESO DE ELIMINACION");
                }
                    
                
            }else{
                 JOptionPane.showMessageDialog(null, "SE HA CANCELADO LA  ACCION DE ELIMINAR");
            }
                
            
        }
    }//GEN-LAST:event_jButtonModificarA16ActionPerformed

    private void Tabla_TiposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla_TiposMouseClicked

    }//GEN-LAST:event_Tabla_TiposMouseClicked

    private void jButtonModificarA14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA14ActionPerformed
        TIPO_diplomnma Buscar = new TIPO_diplomnma();
        Buscar.setNombre_diplo(JTxt_ingreso_diplo.getText());
        if(JTxt_ingreso_diplo.getText().equals("NOMBRE")){
           JOptionPane.showConfirmDialog(null,"DEBE INGRESAR UN NOMBRE");
        }else{
            try {
        ArrayList <TIPO_diplomnma> recibir = new ArrayList();
        recibir = Buscar.buscar();
        System.out.println(recibir.size());
        if(recibir.isEmpty()){
            
        }else{
            limpiar();
            mostrarpersonas(recibir);
        }
        } catch (SQLException ex) {
        Logger.getLogger(administradorInterfaz.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        
    }//GEN-LAST:event_jButtonModificarA14ActionPerformed

    private void jButtonModificarA13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA13ActionPerformed
        
        int seleccionado = -1;
        seleccionado = Tabla_Tipos.getSelectedRow();
        if (seleccionado == -1) {
            JOptionPane.showMessageDialog(null, "Aun no ha seleccionado una fila");
        }else{
            change.setID_diploma(Integer.parseInt(Tabla_Tipos.getValueAt(seleccionado, 0).toString()));
            questnombre.show();
        }
    }//GEN-LAST:event_jButtonModificarA13ActionPerformed

    private void TXT_nuevo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_nuevo_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_nuevo_tipoActionPerformed

    private void jButtonModificarA10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarA10ActionPerformed
        if(TXT_nuevo_tipo.getText().equals("")){
            JOptionPane.showMessageDialog(null,"DEBE ESCRIBIR UN NUEVO NOMBRE PARA LA ESPECIALIDAD");
        
        }else{
            try{
            change.modificar();
            mostrarpersonas(change.mostrar());
            JOptionPane.showMessageDialog(null, "SE HAN GUARDADO LAS MODIFICACIONES CORRECTAMENTE");
            questnombre.dispose();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"HA OCURRIDO UN ERROR");
        }
        }
        
        ;
        
        
    }//GEN-LAST:event_jButtonModificarA10ActionPerformed

    private void txtModificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificar2ActionPerformed

    private void txtModificar2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificar2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificar2MouseExited

    private void txtModificar2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificar2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificar2MouseEntered

    private void txtModificar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificar2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificar2MouseClicked

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarActionPerformed

    private void txtModificarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarMouseExited

    private void txtModificarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarMouseEntered

    private void txtModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarMouseClicked

    private void txtEspecializacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecializacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacionesActionPerformed

    private void txtEspecializacionesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspecializacionesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacionesMouseExited

    private void txtEspecializacionesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspecializacionesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacionesMouseEntered

    private void txtEspecializacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEspecializacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecializacionesMouseClicked

    private void txtAsistentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAsistentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsistentesActionPerformed

    private void txtAsistentesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAsistentesMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsistentesMouseExited

    private void txtAsistentesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAsistentesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAsistentesMouseEntered

    private void txtClientes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientes1ActionPerformed

    private void txtClientes1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClientes1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientes1MouseExited

    private void txtClientes1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtClientes1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientes1MouseEntered

    private void txtAbodados1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAbodados1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbodados1ActionPerformed

    private void txtAbodados1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbodados1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbodados1MouseExited

    private void txtAbodados1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAbodados1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAbodados1MouseEntered

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        jPanel4.setBackground(new Color(135,206,250));
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        jPanel4.setBackground(new Color(25,25,112));
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        jPanel3.setBackground(new Color(135,206,250));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        jPanel3.setBackground(new Color(25,25,112));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
         jPanel5.setBackground(new Color(135,206,250));
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        jPanel5.setBackground(new Color(25,25,112));
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        jPanel6.setBackground(new Color(135,206,250));
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        jPanel6.setBackground(new Color(25,25,112));
    }//GEN-LAST:event_jPanel6MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        JPcrud_abg.setVisible(false);
        JP_fondo_especialidad.setVisible(true);
    }//GEN-LAST:event_jPanel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(administradorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(administradorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(administradorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(administradorInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new administradorInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP_fondo_especialidad;
    private javax.swing.JPanel JPcrud_abg;
    private javax.swing.JPanel JPfondo_Inicial;
    private javax.swing.JTextField JTxt_ingreso_diplo;
    private javax.swing.JTextField TXT_nuevo_tipo;
    private javax.swing.JTable TablaR;
    private javax.swing.JTable Tabla_Tipos;
    private javax.swing.JButton jButtonModificarA10;
    private javax.swing.JButton jButtonModificarA11;
    private javax.swing.JButton jButtonModificarA12;
    private javax.swing.JButton jButtonModificarA13;
    private javax.swing.JButton jButtonModificarA14;
    private javax.swing.JButton jButtonModificarA15;
    private javax.swing.JButton jButtonModificarA16;
    private javax.swing.JButton jButtonModificarA6;
    private javax.swing.JButton jButtonModificarA7;
    private javax.swing.JButton jButtonModificarA8;
    private javax.swing.JButton jButtonModificarA9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPaneCam;
    private javax.swing.JScrollPane jScrollPaneCam1;
    private javax.swing.JDialog questnombre;
    // End of variables declaration//GEN-END:variables
}
