/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package abogados;

import java.awt.Color;

/**
 *
 * @author Steven Zhicay
 */
public class VENTANAC extends javax.swing.JFrame {

    /**
     * Creates new form VENTANAC
     */
    public VENTANAC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnCLIENTE = new javax.swing.JPanel();
        txtCLIENTE = new javax.swing.JLabel();
        btnASISTENTE = new javax.swing.JPanel();
        txtASISTENTE = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnABOGADO = new javax.swing.JPanel();
        txtABOGADO = new javax.swing.JLabel();
        btnADMINISTRADOR = new javax.swing.JPanel();
        txtADMINISTRADOR = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        btnCLIENTE.setBackground(new java.awt.Color(102, 102, 102));
        btnCLIENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCLIENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCLIENTEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCLIENTEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCLIENTEMouseExited(evt);
            }
        });

        txtCLIENTE.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtCLIENTE.setForeground(new java.awt.Color(153, 153, 153));
        txtCLIENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCLIENTE.setText("CLIENTE");

        javax.swing.GroupLayout btnCLIENTELayout = new javax.swing.GroupLayout(btnCLIENTE);
        btnCLIENTE.setLayout(btnCLIENTELayout);
        btnCLIENTELayout.setHorizontalGroup(
            btnCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCLIENTE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnCLIENTELayout.setVerticalGroup(
            btnCLIENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btnASISTENTE.setBackground(new java.awt.Color(102, 102, 102));
        btnASISTENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnASISTENTE.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnASISTENTEMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnASISTENTEMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnASISTENTEMouseExited(evt);
            }
        });

        txtASISTENTE.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtASISTENTE.setForeground(new java.awt.Color(153, 153, 153));
        txtASISTENTE.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtASISTENTE.setText("ASISTENTE");
        txtASISTENTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnASISTENTELayout = new javax.swing.GroupLayout(btnASISTENTE);
        btnASISTENTE.setLayout(btnASISTENTELayout);
        btnASISTENTELayout.setHorizontalGroup(
            btnASISTENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtASISTENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        btnASISTENTELayout.setVerticalGroup(
            btnASISTENTELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtASISTENTE, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("¿Desea registrarse como?");

        btnABOGADO.setBackground(new java.awt.Color(102, 102, 102));
        btnABOGADO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnABOGADOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnABOGADOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnABOGADOMouseExited(evt);
            }
        });

        txtABOGADO.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        txtABOGADO.setForeground(new java.awt.Color(153, 153, 153));
        txtABOGADO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtABOGADO.setText("ABOGADO");
        txtABOGADO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnABOGADOLayout = new javax.swing.GroupLayout(btnABOGADO);
        btnABOGADO.setLayout(btnABOGADOLayout);
        btnABOGADOLayout.setHorizontalGroup(
            btnABOGADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtABOGADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnABOGADOLayout.setVerticalGroup(
            btnABOGADOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtABOGADO, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        btnADMINISTRADOR.setBackground(new java.awt.Color(102, 102, 102));
        btnADMINISTRADOR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnADMINISTRADORMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnADMINISTRADORMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnADMINISTRADORMouseExited(evt);
            }
        });

        txtADMINISTRADOR.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtADMINISTRADOR.setForeground(new java.awt.Color(153, 153, 153));
        txtADMINISTRADOR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtADMINISTRADOR.setText("ADMINISTRADOR");
        txtADMINISTRADOR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout btnADMINISTRADORLayout = new javax.swing.GroupLayout(btnADMINISTRADOR);
        btnADMINISTRADOR.setLayout(btnADMINISTRADORLayout);
        btnADMINISTRADORLayout.setHorizontalGroup(
            btnADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtADMINISTRADOR, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
        );
        btnADMINISTRADORLayout.setVerticalGroup(
            btnADMINISTRADORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtADMINISTRADOR, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnADMINISTRADOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnABOGADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnASISTENTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCLIENTE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnABOGADO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(btnASISTENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnADMINISTRADOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCLIENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCLIENTEMouseClicked
        Registro_u Cliente = new Registro_u();
        Cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCLIENTEMouseClicked

    private void btnCLIENTEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCLIENTEMouseEntered
        btnCLIENTE.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnCLIENTEMouseEntered

    private void btnCLIENTEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCLIENTEMouseExited
        btnCLIENTE.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnCLIENTEMouseExited

    private void btnASISTENTEMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnASISTENTEMouseClicked
        Regi_Asistente Asistente = new Regi_Asistente();
        Asistente.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnASISTENTEMouseClicked

    private void btnASISTENTEMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnASISTENTEMouseEntered
        btnASISTENTE.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnASISTENTEMouseEntered

    private void btnASISTENTEMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnASISTENTEMouseExited
        btnASISTENTE.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnASISTENTEMouseExited

    private void btnABOGADOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnABOGADOMouseClicked
        Regi_abogado Abogado = new Regi_abogado();
        Abogado.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnABOGADOMouseClicked

    private void btnABOGADOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnABOGADOMouseEntered
        btnABOGADO.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnABOGADOMouseEntered

    private void btnABOGADOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnABOGADOMouseExited
        btnABOGADO.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnABOGADOMouseExited

    private void btnADMINISTRADORMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINISTRADORMouseEntered
        btnADMINISTRADOR.setBackground(new Color(0, 0, 0));
    }//GEN-LAST:event_btnADMINISTRADORMouseEntered

    private void btnADMINISTRADORMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINISTRADORMouseExited
        btnADMINISTRADOR.setBackground(new Color(102, 102, 102));
    }//GEN-LAST:event_btnADMINISTRADORMouseExited

    private void btnADMINISTRADORMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnADMINISTRADORMouseClicked
        Radministrador Admin = new Radministrador();
        Admin.setVisible(true);
          VentanaPrincipal1 principal = new VentanaPrincipal1();
        principal.setVisible(false);
        dispose();
        dispose();
    }//GEN-LAST:event_btnADMINISTRADORMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VENTANAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VENTANAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VENTANAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VENTANAC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VENTANAC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnABOGADO;
    private javax.swing.JPanel btnADMINISTRADOR;
    private javax.swing.JPanel btnASISTENTE;
    private javax.swing.JPanel btnCLIENTE;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtABOGADO;
    private javax.swing.JLabel txtADMINISTRADOR;
    private javax.swing.JLabel txtASISTENTE;
    private javax.swing.JLabel txtCLIENTE;
    // End of variables declaration//GEN-END:variables
}
